### PR TITLE
Revert language changes

### PR DESCRIPTION
**Pull request by greatislander**
This PR temporarily removes the update POT action (ref: #45).

### CODE REVIEW

**Comment by greatislander** [comment]
@SteelWagstaff Can you restart this build?

**Comment by SteelWagstaff** [comment]
@greatislander It'll keep failing -- the build errored because of a Composer 2 upgrade that we haven't accounted for yet in this plugin. I'm going to revert for now.

**Comment by SteelWagstaff** [comment]
Actually, I think we can fix by declaring a specific composer version. Trying to find the PR from Ho Man that did this for another repo.

**Comment by SteelWagstaff** [comment]
Here's what @ho-man-chan did when we saw a similar error in Aldine: https://github.com/pressbooks/pressbooks-aldine/pull/223/files

**Review by SteelWagstaff — APPROVED** [review]
LGTM

**Pull request merged**
